CREATE TABLE `user` (
    user_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    email VARCHAR(255) NOT NULL UNIQUE,
    password VARCHAR(255) NOT NULL,
    user_name VARCHAR(100) NOT NULL,
    user_level INTEGER NOT NULL,
    bio VARCHAR(1000),
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE user_stats (
    user_id BIGINT PRIMARY KEY,
    total_games INTEGER NOT NULL DEFAULT 0,
    wins INTEGER NOT NULL DEFAULT 0,
    losses INTEGER NOT NULL DEFAULT 0,
    rating INTEGER NOT NULL DEFAULT 1000,
    FOREIGN KEY (user_id) REFERENCES `user` (user_id)
);

CREATE TABLE game_completion (
    game_id CHAR(36) PRIMARY KEY,
    room_id BIGINT NOT NULL,
    winner_faction VARCHAR(16) NOT NULL,
    completed_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

CREATE TABLE game_room (
    room_id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    host_user_id BIGINT NOT NULL,
    title VARCHAR(100) NOT NULL,
    room_password VARCHAR(255),
    max_players TINYINT NOT NULL,
    status VARCHAR(20) NOT NULL,
    created_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (host_user_id) REFERENCES `user` (user_id)
);

CREATE TABLE room_members (
    room_id BIGINT NOT NULL,
    user_id BIGINT NOT NULL,
    is_ready BOOLEAN NOT NULL DEFAULT FALSE,
    role VARCHAR(20),
    is_alive BOOLEAN NOT NULL DEFAULT TRUE,
    joined_time TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY (room_id, user_id),
    FOREIGN KEY (room_id) REFERENCES game_room (room_id),
    FOREIGN KEY (user_id) REFERENCES `user` (user_id)
);
